const fs = require("fs");
const path = require("path");

const FILE_PATH = path.join(__dirname, "src", "components", "ProjectDashboard.jsx");
const ALT_PATH  = path.join(__dirname, "src", "ProjectDashboard.jsx");
const actualPath = fs.existsSync(FILE_PATH) ? FILE_PATH : ALT_PATH;

if (!fs.existsSync(actualPath)) {
  console.error(`❌ Could not find ProjectDashboard.jsx`);
  process.exit(1);
}

let source = fs.readFileSync(actualPath, "utf8");
const originalSource = source;

const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
const backupPath = actualPath.replace(/\.jsx$/, `.jsx.bak-simplify-${timestamp}`);
fs.writeFileSync(backupPath, originalSource, "utf8");
console.log(`✅ Backup saved to: ${backupPath}`);

const replacements = [
  {
    label: "Compliance Score hint text",
    from: "Suggested from parsed risk levels — adjust if needed.",
    to: "Estimated automatically based on the risks found in your report. You can change it below if needed.",
  },
  {
    label: 'Compliance Score button ("Override" → "Set manually")',
    from: '{project?.complianceScore != null ? "Edit" : "Override"}',
    to: '{project?.complianceScore != null ? "Edit" : "Set manually"}',
  },
  {
    label: "No risk data message",
    from: "No risk data yet — generate a report or set manually.",
    to: "No risk information yet. Upload a document to get a report, or enter a score yourself below.",
  },
  {
    label: "Budget Utilization hint text",
    from: "Tracked manually — not generated by an agent yet.",
    to: "You enter this yourself — it isn't calculated automatically.",
  },
];

let applied = 0;
let skipped = 0;

for (const { label, from, to } of replacements) {
  if (source.includes(from)) {
    source = source.split(from).join(to);
    console.log(`✅ Simplified: ${label}`);
    applied++;
  } else if (source.includes(to)) {
    console.log(`⏭️  Already simplified: ${label}`);
    skipped++;
  } else {
    console.log(`❌ NOT FOUND (skipped, nothing changed for this one): ${label}`);
    skipped++;
  }
}

if (source !== originalSource) {
  fs.writeFileSync(actualPath, source, "utf8");
  console.log(`\n💾 ProjectDashboard.jsx updated. (${applied} wording change(s) applied, ${skipped} skipped/not found)`);
} else {
  console.log("\n⚠️  No changes were made.");
}